FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# sessions_service

The Sessions Service provides facilities to create a session, tie a 
session to one or more user IDs, tie a session to one or more
third-party identities, and create and authenticate login
credentials via a separate Authentication Service. 


## Root [/]

The root path returns a map of available service endpoints. External 
services can query the root path for a directory of 
endpoints, rather than hard-code URLs, allowing for more flexible 
service discovery and use. 


### Retrieve the entry points [GET]

+ Response 200 (application/json)

        {
            "v1": {
                "credentials_url":  "/api/v1/sessions/:id/credentials,
                "logins_url":       "/api/v1/sessions/:id/logins",
                "identities_url":   "/api/v1/sessions/:id/identities",
                "session_url":      "/api/v1/sessions/:id",
                "sessions_url":     "/api/v1/sessions"
            }
        }


## Sessions [/api/v1/sessions]

### Create a new Session [POST]

Request a new session ID and user ID pair. 

This action returns a 200 status code and a JSON body. 

+ Response 200 (application/json)
    + Attributes
        - session (Session)

+ Response 403 (application/json)

        
## Session [/api/v1/sessions/{session_id}]

+ Parameters
    + session_id: `12345` (number, required) - ID of the Session
    
### Get an existing Session [GET] 

Find all information associated with a session ID. 

Success returns a 200 status code and a JSON body. 

+ Response 200 (application/json)
    + Attributes
        - session (Session)


### Delete an existing Session[DELETE]

Destroy an existing session and all credentials associated with it. 

+ Response 200 (application/json)
    + Attributes
        - session (Session)

+ Response 404 (application/json)


## Identity [/api/v1/sessions/{session_id}/identities]

### Request a new Oauth-based identity[POST]

+ Request
    + Attributes 
        - type (Identity, required) 

+ Response 200 (application/json)
    + Attributes
        - session (Session)


## Login [/api/v1/sessions/{session_id}/logins]

+ Parameter
    + session_id: `12345` (number, required)


### Create a new Login [POST]

+ Request (application/json)
    + Attributes
        - login (Login)
        
+ Response 201 (application/json)
    + Attributes
        - session (Session)

+ Response 403 (application/json)

+ Response 409 (application/json)


### Authenticate an existing Login [GET]

+ Request (application/json)
    + Attributes
        - login (Login)
        
+ Response 200 (application/json)
    + Attributes
        - session (Session)

+ Response 401 (application/json)


## Credential [/api/v1/sessions/{session_id}/credentials]

+ Parameter
    + session_id: `12345` (number, required)


### Create a new Credential [POST]

+ Request (application/json)
    + Attributes
        - credential (Credential)
        
+ Response 201 (application/json)
    + Attributes
        - session (Session)


### Lookup an existing Credential [GET]

+ Request (application/json)
    + Attributes
        - credential (Credential, required)
        
+ Response 200 (application/json)
    + Attributes
        - session (Session)
        
+ Response 404 (application/json)


### Delete an existing Credential [DELETE]

+ Request (application/json)
    + Attributes
        - credential (Credential, required)

+ Response 200 (application/json)
    + Attributes
        - session (Session)

+ Response 401 (application/json)

        Credential cannot be deleted, likely because the session is not associated with the credential. 
        
+ Response 404 (application/json)

        Credential cannot be found. 


# Data Structures


## Credential (object)

- user_id: `12345` (number, required) - The unique ID of the user. 
- type (enum[string], required)
    - facebook - A user created via Facebook.
    - twitter - A user created via Twitter. 
    - google - A user created via Google. 
    - login - A user created via the site directly. 


## Identity (object)

- type (enum[string], required)
    - facebook - A user created via Facebook.
    - twitter - A user created via Twitter. 
    - google - A user created via Google. 


## Login (object)

- email: `joe@example.org` (string, required) - An email address.
- password: `password` (string, required) - A password. 


## Session (object)

- session_id: `12345` (number, required) - The session ID. 
- credentials (array[Credential], required)