FORMAT: 1A
HOST: http://session-service.rentpathservices.com/

# sessions_service

The Sessions Service provides facilities to create a session, tie a
session to one or more user IDs, tie a session to one or more
third-party identities, and create and authenticate login
credentials via a separate Authentication Service.


## Root [/]

The root path returns a map of available service endpoints. External
services can query the root path for a directory of
endpoints rather than hard-code URLs, allowing for more flexible
service discovery and use.

### Retrieve the entry points [GET]

+ Request JSON Message
    + Headers
    
            Accept: application/vnd.api+json
            
+ Response 200 (application/vnd.api+json)

        {
            "data": { 
                "v1": {
                    "links": {
                        "credentialsUrl":   "/api/v1/sessions/:id/credentials",
                        "loginsUrl":        "/api/v1/sessions/:id/logins",
                        "identitiesUrl":    "/api/v1/sessions/:id/identities",
                        "sessionUrl":       "/api/v1/sessions/:id",
                        "sessionsUrl":      "/api/v1/sessions"
                    }
                }
            }
        }

+ Response 401 (application/vnd.api+json)
        
+ Response 406 (application/vnd.api+json)

        {
            "errors": [
                { 
                    "status": 406,
                    "title": "Accept header is not application/vnd.api+json" 
                }
            ]
        }


## Sessions [/api/v1/sessions]

A session represents a visit to the site. Each visit is tied
to a person and the visit represents that person until the 
person destroys the visit or the visit is purged upon expiration. 

### Create a new Session [POST]

Request a new session ID and user ID pair.

+ Response 201 (application/vnd.api+json)
    + Headers 
    
            Location: /api/v1/sessions/{session_id}
    
    + Attributes
        - data (Session)
            
+ Response 403 (application/vnd.api+json)


## Session [/api/v1/sessions/{session_id}]

+ Parameters
    + session_id: `12345` (number, required) - ID of the Session

### Get an existing Session [GET]

Find all information associated with a session ID.

+ Response 200 (application/vnd.api+json)
    + Attributes
        - data (Session)

+ Response 401 (application/vnd.api+json)

+ Response 404 (application/vnd.api+json)

### Delete an existing Session[DELETE]

Destroy an existing session and all credentials associated with it.

+ Response 200 (application/vnd.api+json)
    + Attributes
        - data (Session)

+ Response 404 (application/vnd.api+json)


## Identity [/api/v1/sessions/{session_id}/identities]

### Request a new Oauth-based identity[POST]

+ Request
    + Attributes
        - data (Identity, required)

+ Response 201 (application/vnd.api+json)
    + Headers 
    
            Location: /api/v1/sessions/{session_id}/identities/{identity_id}
            
    + Attributes
        - data (Session)
            - redirect_uri (string)

+ Response 401 (application/vnd.api+json)

+ Response 403 (application/vnd.api+json)

+ Response 409 (application/vnd.api+json)


## Login [/api/v1/sessions/{session_id}/logins]

+ Parameter
    + session_id: `12345` (number, required)

### Create a new Login [POST]

+ Request (application/json)
    + Attributes
        - login (Login)

+ Response 201 (application/vnd.api+json)

    + Headers 
    
            Location: /api/v1/sessions/{session_id}/logins/{login_id}

    + Attributes
        - session (Session)

+ Response 401 (application/vnd.api+json)

+ Response 403 (application/vnd.api+json)

+ Response 409 (application/vnd.api+json)

### Authenticate an existing Login [GET]

+ Request (application/json)
    + Attributes
        - login (Login)

+ Response 200 (application/vnd.api+json)
    + Attributes
        - session (Session)

+ Response 401 (application/vnd.api+json)


## Credential [/api/v1/sessions/{session_id}/credentials]

+ Parameter
    + session_id: `12345` (number, required)

### Create a new Credential [POST]

+ Request (application/json)
    + Attributes
        - credential (Credential)

+ Response 201 (application/vnd.api+json)
    + Headers 
    
            Location: /api/v1/sessions/{session_id}/identities/{identity_id}
            
    + Attributes
        - session (Session)

+ Response 401 (application/vnd.api+json)

+ Response 403 (application/vnd.api+json)

+ Response 404 (application/vnd.api+json)

### Lookup an existing Credential [GET]

+ Request (application/json)
    + Attributes
        - credential (Credential, required)

+ Response 200 (application/vnd.api+json)
    + Attributes
        - session (Session)

+ Response 401 (application/vnd.api+json)

+ Response 403 (application/vnd.api+json)

+ Response 404 (application/vnd.api+json)

### Delete an existing Credential [DELETE]

+ Request (application/json)
    + Attributes
        - credential (Credential, required)

+ Response 200 (application/vnd.api+json)
    + Attributes
        - session (Session)

+ Response 401 (application/vnd.api+json)

+ Response 403 (application/vnd.api+json)
        
+ Response 404 (application/vnd.api+json)


# Data Structures

## Credential (object)

- id: `abcdefgh123` (string, required) - The unique ID of the user.
- type: `credentials`
- attributes
    - provider (enum[string], required)
        - facebook - A user created via Facebook.
        - twitter - A user created via Twitter.
        - google - A user created via Google.
        - login - A user created via the site directly.


## Error (object) 
- status: `404` (string, required) - The HTTP status code applicable to this error
- title: `Resource not found` (string, required) - A short summary of the problem that does not change from occurrence to 
occurrence of the problem, except for purposes of localization
- detail: `An explanation of the problem` - More detail about the issue, can be localized


## Identity (object)

- id: `abcdefgh123` (string, required) - The unique ID of the resource.
- type: `identities` 
- attributes
    - provider (enum[string], required)
        - facebook - A user created via Facebook.
        - twitter - A user created via Twitter.
        - google - A user created via Google.


## Link (object)

- self: `http://example.com/some/id` (string, optional) - A URL pointing to the resource in the response. 
- related (Related, optional)


## Login (object)

- attributes
    - email: `joe@example.org` (string, required) - An email address.
    - password: `password` (string, required) - A password.


## Related (object)

- href: `http://example.com/some/path` (string, optional) - A URL. 
- meta (object, optional) - A collection of metadata for the link. 


## Session (object)

- id: `12345` (number, required) - The session ID.
- type: `sessions`
- relationships (array[Credential], required)